#!/usr/bin/env bash
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

print_usage() {
      echo "  Console:         typedb console [--help]"
}

# =============================================
# main routine
# =============================================

[[ $(readlink $0) ]] && path=$(readlink $0) || path=$0
TYPEDB_HOME=$(cd "$(dirname "${path}")" && pwd -P)

case "$1" in
    console)
       # exec replaces current shell process with java so no commands after these ones will ever get executed
        TYPEDB_CONSOLE_BIN="${TYPEDB_HOME}/console/typedb_console_bin"
        exec ${TYPEDB_CONSOLE_BIN} "${@:2}"
        ;;
    "")
        echo "Missing argument. Possible commands are:"
        print_usage
        exit 1
        ;;
    *)
        echo "Invalid argument: $1. Possible commands are: "
        print_usage
        exit 1
        ;;
esac
